# ===============================
# SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONEXIÓN A LA BASE DE DATOS (POSTGRESQL)
# ===============================
# TODO: Cambia "hotel_db", "postgres" y "tu_contraseña" por tus datos reales
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_db
spring.datasource.username=postgres
spring.datasource.password=database
spring.datasource.driver-class-name=org.postgresql.Driver

# "update" sincroniza tus clases @Entity con la DB sin borrar datos.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jackson.serialization.indent-output=true